/**
 * Referral Letter API Client
 * Provides typed wrappers for POST /api/referral/generate and POST /api/referral/pdf
 */

import { getToken } from "./auth";

const API_BASE = import.meta.env.VITE_API_URL || "https://askainurse.com";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface VitalScanData {
  heartRate?: number | null;
  bloodPressure?: string | null;
  spo2?: number | null;
}

export interface ReferralGenerateRequest {
  // Required
  chatHistory: Array<{ role: "user" | "assistant"; content: string }>;
  userType: "guest" | "authenticated";
  reasonForReferral: string;
  urgency: "routine" | "urgent" | "two-week-wait";
  specialistSpecialty: string;
  specificRequest: "assess" | "diagnose" | "treat" | "second-opinion";

  // Optional — backend fills intelligently from chatHistory if missing
  patientName?: string | null;
  patientDOB?: string | null;
  patientSex?: string | null;
  patientContact?: string | null;
  patientInsurance?: string | null;
  specialistName?: string | null;
  specialistClinic?: string | null;
  historyOfComplaint?: string | null;
  pastMedicalHistory?: string | null;
  currentMedications?: string | null;
  allergies?: string | null;
  vitalScanData?: VitalScanData | null;
  investigationsDone?: string | null;
  enclosures?: string | null;
}

export interface ReferralLetter {
  referenceNumber: string;
  dateOfIssue: string;

  reasonForReferral: string;
  urgency: "routine" | "urgent" | "two-week-wait";
  specialistSpecialty: string;
  specificRequest: "assess" | "diagnose" | "treat" | "second-opinion";

  patientName: string | null;
  patientDOB: string | null;
  patientSex: string | null;
  patientContact: string | null;
  patientInsurance: string | null;

  specialistName: string | null;
  specialistClinic: string | null;

  historyOfComplaint: string | null;
  pastMedicalHistory: string | null;
  currentMedications: string | null;
  allergies: string | null;
  vitalScanData: VitalScanData | null;

  /** AI-generated by backend — never sent from frontend */
  examinationFindings: string;
  investigationsDone: string | null;
  /** AI-generated by backend — never sent from frontend */
  provisionalDiagnosis: string;
  enclosures: string | null;

  referringDoctorName: string;
  referringDoctorSpecialty: string;
  referringDoctorAddress: string;
  referringDoctorTel: string;
  referringDoctorID: string;

  userType: "guest" | "authenticated";
  aiAssistedFields: string[];
}

export interface ReferralGenerateResponse {
  success: boolean;
  referral: ReferralLetter;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildHeaders(includeAuth = true): Record<string, string> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (includeAuth) {
    const token = getToken();
    if (token) headers["Authorization"] = `Bearer ${token}`;
  }
  return headers;
}

// ─── API ─────────────────────────────────────────────────────────────────────

/**
 * POST /api/referral/generate
 *
 * Sends the chat history + clinical data to the backend.
 * The backend calls Anthropic to:
 *   - Fill any missing optional fields from conversation context
 *   - Generate provisionalDiagnosis (always AI-generated)
 *   - Generate examinationFindings (always AI-generated)
 *
 * If the user is authenticated and a valid JWT exists, the record is also
 * saved to the database and will appear in the user's Assessments history.
 *
 * @param payload  Full referral generate request body
 * @returns        Structured referral JSON with all fields filled
 */
export async function generateReferral(
  payload: ReferralGenerateRequest
): Promise<ReferralLetter> {
  const res = await fetch(`${API_BASE}/api/referral/generate`, {
    method: "POST",
    headers: buildHeaders(true),
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    let errMsg = `Referral generate failed (${res.status})`;
    try {
      const errJson = JSON.parse(errText);
      errMsg = errJson.error || errJson.message || errMsg;
    } catch {
      if (errText) errMsg = errText;
    }
    throw new Error(errMsg);
  }

  const data: ReferralGenerateResponse = await res.json();
  return data.referral;
}

/**
 * POST /api/referral/pdf
 *
 * Accepts the filled referral JSON returned by generateReferral() and
 * returns a binary PDF Blob matching the Clinique de la Brisée letter layout.
 *
 * Fields marked (AI-assisted) in the PDF: provisionalDiagnosis, examinationFindings.
 *
 * @param referral  The filled ReferralLetter object from generateReferral()
 * @returns         PDF file as a Blob (application/pdf)
 */
export async function downloadReferralPDF(
  referral: ReferralLetter
): Promise<Blob> {
  const res = await fetch(`${API_BASE}/api/referral/pdf`, {
    method: "POST",
    headers: buildHeaders(true),
    body: JSON.stringify(referral),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    let errMsg = `Referral PDF generation failed (${res.status})`;
    try {
      const errJson = JSON.parse(errText);
      errMsg = errJson.error || errJson.message || errMsg;
    } catch {
      if (errText) errMsg = errText;
    }
    throw new Error(errMsg);
  }

  return res.blob();
}

export interface ReferralSessionResponse {
  success: boolean;
  referral_id: number;
  reference_number: string;
  referral: ReferralLetter;
}

export async function createReferralSession(
  payload: ReferralGenerateRequest
): Promise<ReferralSessionResponse> {
  const res = await fetch(`${API_BASE}/api/referral/create-session`, {
    method: "POST",
    headers: buildHeaders(true),
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    let errMsg = `Referral create session failed (${res.status})`;
    try {
      const errJson = JSON.parse(errText);
      errMsg = errJson.error || errJson.message || errMsg;
    } catch {
      if (errText) errMsg = errText;
    }
    throw new Error(errMsg);
  }

  return res.json();
}

export async function saveReferralEmail(
  id: string | number,
  email: string
): Promise<{ success: boolean; delivery_email: string }> {
  const res = await fetch(`${API_BASE}/api/referral/${encodeURIComponent(id)}/email`, {
    method: "POST",
    headers: buildHeaders(true),
    body: JSON.stringify({ email }),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    let errMsg = `Save delivery email failed (${res.status})`;
    try {
      const errJson = JSON.parse(errText);
      errMsg = errJson.error || errJson.message || errMsg;
    } catch {
      if (errText) errMsg = errText;
    }
    throw new Error(errMsg);
  }

  return res.json();
}

export interface ReferralStatusResponse {
  payment_status: "pending" | "paid" | "failed";
  email_status: "pending" | "sent" | "failed";
  reference_code: string;
}

export async function getReferralStatus(
  id: string | number
): Promise<ReferralStatusResponse> {
  const res = await fetch(`${API_BASE}/api/referral/status/${encodeURIComponent(id)}`, {
    method: "GET",
    headers: buildHeaders(true),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    let errMsg = `Get referral status failed (${res.status})`;
    try {
      const errJson = JSON.parse(errText);
      errMsg = errJson.error || errJson.message || errMsg;
    } catch {
      if (errText) errMsg = errText;
    }
    throw new Error(errMsg);
  }

  return res.json();
}

export async function generateAndDownloadPDF(
  payload: ReferralGenerateRequest
): Promise<ReferralLetter> {
  const referral = await generateReferral(payload);
  const blob = await downloadReferralPDF(referral);

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `referral-${referral.referenceNumber}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);

  return referral;
}

// ─── Grouped export (matches existing apiClient.ts style) ─────────────────────

export const referralApi = {
  createSession: createReferralSession,
  saveEmail: saveReferralEmail,
  getStatus: getReferralStatus,
  generate: generateReferral,
  downloadPDF: downloadReferralPDF,
  generateAndDownloadPDF,
};
