/**
 * Generate a branded Cira PDF from report data
 * Uses jsPDF for client-side PDF generation
 */
import jsPDF from "jspdf";

// Cira brand colors (HSL converted to RGB)
const COLORS = {
  primary: [196, 64, 157] as [number, number, number],       // hsl(319,65%,56%) → pink
  primaryLight: [251, 100, 182] as [number, number, number],  // lighter pink
  foreground: [30, 20, 46] as [number, number, number],      // dark purple-black
  muted: [130, 117, 107] as [number, number, number],        // muted text
  border: [220, 213, 206] as [number, number, number],       // light border
  background: [247, 244, 239] as [number, number, number],   // cream bg
  cardBg: [252, 250, 248] as [number, number, number],       // slightly off-white card
  white: [255, 255, 255] as [number, number, number],
  emerald: [16, 185, 129] as [number, number, number],
  emeraldLight: [209, 250, 229] as [number, number, number],
  amber: [217, 119, 6] as [number, number, number],
  amberLight: [254, 243, 199] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  redLight: [254, 226, 226] as [number, number, number],
  purple: [158, 29, 244] as [number, number, number],
  purpleLight: [243, 232, 255] as [number, number, number],
};

function drawLine(doc: jsPDF, y: number, x1 = 20, x2 = 190) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(x1, y, x2, y);
}

function checkPage(doc: jsPDF, y: number, needed = 20): number {
  if (y + needed > 275) {
    doc.addPage();
    return 20;
  }
  return y;
}

function addSection(doc: jsPDF, title: string, y: number): number {
  y = checkPage(doc, y, 15);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.primary);
  doc.text(title.toUpperCase(), 20, y);
  y += 2;
  drawLine(doc, y, 20, 190);
  y += 6;
  doc.setTextColor(...COLORS.foreground);
  return y;
}

function addParagraph(doc: jsPDF, text: string, y: number, indent = 20): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.foreground);
  const lines = doc.splitTextToSize(text || "—", 165);
  for (const line of lines) {
    y = checkPage(doc, y);
    doc.text(line, indent, y);
    y += 4.5;
  }
  return y;
}

function addBullet(doc: jsPDF, text: string, y: number): number {
  y = checkPage(doc, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.foreground);
  doc.text("•", 24, y);
  const lines = doc.splitTextToSize(text, 155);
  for (const line of lines) {
    y = checkPage(doc, y);
    doc.text(line, 30, y);
    y += 4.5;
  }
  return y;
}

function addHeader(doc: jsPDF, title: string, type: string, date: string) {
  // Top bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, 210, 3, "F");

  // Logo text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.primary);
  doc.text("Cira", 20, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text("AI Health Nurse", 42, 18);

  // Format date nicely
  const formattedDate = (() => {
    try {
      const d = new Date(date);
      if (!isNaN(d.getTime())) return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
    } catch {}
    return date;
  })();

  // Report type badge + date on separate lines
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.primary);
  doc.text(type.toUpperCase(), 190, 10, { align: "right" });
  doc.setTextColor(...COLORS.muted);
  doc.text(formattedDate, 190, 15, { align: "right" });

  drawLine(doc, 24);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.foreground);
  const titleLines = doc.splitTextToSize(title, 170);
  let y = 32;
  for (const line of titleLines) {
    doc.text(line, 20, y);
    y += 6;
  }

  return y + 4;
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    // Bottom bar
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 294, 210, 3, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.muted);
    doc.text("Generated by Cira AI Health Nurse  •  For informational purposes only  •  Not a medical diagnosis", 105, 290, { align: "center" });
    doc.text(`Page ${i} of ${pages}`, 190, 290, { align: "right" });
  }
}

export function generateQuickAssessmentPdf(report: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const data = report.data || {};
  const date = report.date || report.created_at || new Date().toLocaleDateString();

  let y = addHeader(doc, report.title || "Quick Assessment Report", "Quick Assessment", date);

  // Summary
  y = addSection(doc, "Summary", y);
  y = addParagraph(doc, data.summary || report.summary || "", y);
  y += 4;

  // Possible Conditions
  if (data.possible_conditions?.length) {
    y = addSection(doc, "Possible Conditions", y);
    for (const cond of data.possible_conditions) {
      y = checkPage(doc, y, 14);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(cond.name || "", 24, y);

      if (cond.likelihood) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.muted);
        doc.text(`(${cond.likelihood})`, 24 + doc.getTextWidth((cond.name || "") + "  "), y);
        doc.setTextColor(...COLORS.foreground);
      }
      y += 5;
      if (cond.explanation) {
        y = addParagraph(doc, cond.explanation, y, 28);
      }
      y += 2;
    }
    y += 2;
  }

  // Recommended Actions
  if (data.recommended_actions?.length) {
    y = addSection(doc, "Recommended Actions", y);
    for (const action of data.recommended_actions) {
      y = addBullet(doc, action, y);
    }
    y += 4;
  }

  // Follow-up
  if (data.follow_up) {
    y = addSection(doc, "Follow-Up", y);
    y = addParagraph(doc, data.follow_up, y);
  }

  // Confidence
  if (data.confidence_score != null) {
    y = checkPage(doc, y, 12);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Confidence Score: ${data.confidence_score}%`, 20, y);
  }

  addFooter(doc);
  return doc;
}

export function generateDetailedReportPdf(report: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const data = report.data || {};
  const date = report.date || report.created_at || new Date().toLocaleDateString();

  let y = addHeader(doc, report.title || "Detailed Assessment Report", "Detailed Assessment", date);

  // Patient Summary
  if (data.patient_summary) {
    y = addSection(doc, "Patient Summary", y);
    y = addParagraph(doc, data.patient_summary, y);
    y += 4;
  }

  // Chief Complaint
  if (data.chief_complaint) {
    y = addSection(doc, "Chief Complaint", y);
    y = addParagraph(doc, data.chief_complaint, y);
    y += 4;
  }

  // HPI
  if (data.history_of_present_illness) {
    y = addSection(doc, "History of Present Illness", y);
    y = addParagraph(doc, data.history_of_present_illness, y);
    y += 4;
  }

  // Review of Systems
  if (data.review_of_systems?.length) {
    y = addSection(doc, "Review of Systems", y);
    for (const ros of data.review_of_systems) {
      y = checkPage(doc, y, 10);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.text(ros.system || "", 24, y);
      y += 4.5;
      y = addParagraph(doc, ros.findings || "", y, 28);
      y += 2;
    }
    y += 2;
  }

  // Assessment
  if (data.assessment) {
    y = addSection(doc, "Assessment", y);
    if (data.assessment.primary_diagnosis) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Primary Diagnosis:", 24, y);
      doc.setFont("helvetica", "normal");
      doc.text(data.assessment.primary_diagnosis, 60, y);
      y += 5;
    }
    if (data.assessment.severity) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Severity:", 24, y);
      doc.setFont("helvetica", "normal");
      const sev = data.assessment.severity;
      const sevColor = sev === "severe" ? COLORS.red : sev === "moderate" ? COLORS.amber : COLORS.emerald;
      doc.setTextColor(...sevColor);
      doc.text(sev.charAt(0).toUpperCase() + sev.slice(1), 45, y);
      doc.setTextColor(...COLORS.foreground);
      y += 5;
    }
    if (data.assessment.differential_diagnoses?.length) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Differential Diagnoses:", 24, y);
      y += 5;
      for (const dd of data.assessment.differential_diagnoses) {
        y = addBullet(doc, `${dd.name}${dd.likelihood ? ` — ${dd.likelihood}` : ""}`, y);
      }
    }
    y += 4;
  }

  // Plan
  if (data.plan) {
    y = addSection(doc, "Treatment Plan", y);

    if (data.plan.immediate_actions?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Immediate Actions", 24, y);
      y += 5;
      for (const a of data.plan.immediate_actions) y = addBullet(doc, a, y);
      y += 3;
    }
    if (data.plan.medications_suggested?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Medications Suggested", 24, y);
      y += 5;
      for (const m of data.plan.medications_suggested) y = addBullet(doc, m, y);
      y += 3;
    }
    if (data.plan.lifestyle_recommendations?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Lifestyle Recommendations", 24, y);
      y += 5;
      for (const l of data.plan.lifestyle_recommendations) y = addBullet(doc, l, y);
      y += 3;
    }
    if (data.plan.follow_up) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Follow-Up", 24, y);
      y += 5;
      y = addParagraph(doc, data.plan.follow_up, y, 28);
    }
    y += 4;
  }

  // Red Flags
  if (data.red_flags?.length) {
    y = addSection(doc, "⚠ Red Flags", y);
    for (const flag of data.red_flags) {
      y = checkPage(doc, y);
      doc.setTextColor(...COLORS.red);
      y = addBullet(doc, flag, y);
      doc.setTextColor(...COLORS.foreground);
    }
    y += 4;
  }

  // Confidence
  if (data.confidence_score != null) {
    y = checkPage(doc, y, 12);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Confidence Score: ${data.confidence_score}%`, 20, y);
  }

  addFooter(doc);
  return doc;
}

export function downloadReportPdf(report: any) {
  const isDetailed = (report.type || "").toLowerCase().includes("detailed");
  const doc = isDetailed
    ? generateDetailedReportPdf(report)
    : generateQuickAssessmentPdf(report);

  const filename = `Cira_${(report.type || "Report").replace(/\s+/g, "_")}_${report.id || Date.now()}.pdf`;
  doc.save(filename);
}

// ─── Vitals Scan PDF ────────────────────────────────────────────

interface VitalScanData {
  id?: string;
  created_at?: string;
  date?: string;
  heart_rate?: number;
  systolic_bp?: number;
  diastolic_bp?: number;
  hrv_sdnn?: number;
  breathing_rate?: number;
  stress_index?: number;
  cardiac_workload?: number;
  parasympathetic_activity?: number;
  bmi?: number;
  vascular_age?: number;
  wellness_score?: number;
  waist_to_height_ratio?: number;
  body_fat_percentage?: number;
  basal_metabolic_rate?: number;
  body_shape_index?: number;
  total_daily_energy_expenditure?: number;
  cv_disease_risk?: number;
  coronary_heart_disease_risk?: number;
  stroke_risk?: number;
  heart_failure_risk?: number;
  diabetes_risk?: number;
  fatty_liver_risk?: number;
  hard_cv_event_risk?: number;
  [key: string]: any;
}

function formatScanDate(d?: string): string {
  if (!d) return "N/A";
  try {
    const date = new Date(d);
    if (!isNaN(date.getTime())) return date.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
  } catch {}
  return d;
}

function val(v: number | null | undefined, decimals = 0): string {
  if (v == null) return "—";
  return decimals > 0 ? Number(v).toFixed(decimals) : String(Math.round(v));
}

function riskLabel(v: number | null | undefined): string {
  if (v == null) return "—";
  if (v < 10) return "Low";
  if (v < 25) return "Moderate";
  return "High";
}

function fattyLiverLabel(v: number | null | undefined): string {
  if (v == null) return "—";
  if (v === 0) return "Low";
  if (v === 1) return "Moderate";
  if (v === 2) return "High";
  return riskLabel(v);
}

function riskColor(level: string): [number, number, number] {
  if (level === "Low") return COLORS.emerald;
  if (level === "Moderate") return COLORS.amber;
  if (level === "High") return COLORS.red;
  return COLORS.muted;
}

function drawVitalRow(doc: jsPDF, label: string, value: string, unit: string, y: number, x = 24): number {
  y = checkPage(doc, y, 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(label, x, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.foreground);
  doc.text(value, x + 75, y);
  if (unit && value !== "—") {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(unit, x + 75 + doc.getTextWidth(value + " "), y);
  }
  return y + 5.5;
}

function drawRiskRow(doc: jsPDF, label: string, level: string, y: number, x = 24): number {
  y = checkPage(doc, y, 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(label, x, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...riskColor(level));
  doc.text(level, x + 75, y);
  doc.setTextColor(...COLORS.foreground);
  return y + 5.5;
}

function addScanBlock(doc: jsPDF, scan: VitalScanData, y: number, showDate = true): number {
  if (showDate) {
    y = checkPage(doc, y, 10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.primary);
    doc.text(formatScanDate(scan.created_at || scan.date), 20, y);
    y += 2;
    drawLine(doc, y);
    y += 6;
  }

  // Vital Signs
  const vitals: [string, string, string][] = [
    ["Blood Pressure", scan.systolic_bp && scan.diastolic_bp ? `${Math.round(scan.systolic_bp)}/${Math.round(scan.diastolic_bp)}` : "—", "mmHg"],
    ["Heart Rate", val(scan.heart_rate), "bpm"],
    ["Heart Rate Variability", val(scan.hrv_sdnn), "ms"],
    ["Breathing Rate", val(scan.breathing_rate), "/min"],
    ["Stress Index", val(scan.stress_index), "/100"],
    ["Cardiac Workload", val(scan.cardiac_workload), ""],
    ["Parasympathetic Activity", val(scan.parasympathetic_activity), ""],
  ];

  const hasVitals = vitals.some(([, v]) => v !== "—");
  if (hasVitals) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...COLORS.foreground);
    y = checkPage(doc, y, 8);
    doc.text("Vital Signs", 20, y);
    y += 5;
    for (const [label, value, unit] of vitals) {
      if (value !== "—") y = drawVitalRow(doc, label, value, unit, y);
    }
    y += 3;
  }

  // Health Indices
  const indices: [string, string, string][] = [
    ["Body Mass Index", val(scan.bmi, 1), "kg/m²"],
    ["Vascular Age", val(scan.vascular_age), "yrs"],
    ["Wellness Score", val(scan.wellness_score), "/100"],
    ["Waist-to-Height Ratio", val(scan.waist_to_height_ratio, 2), ""],
    ["Body Fat Percentage", val(scan.body_fat_percentage, 1), "%"],
    ["Basal Metabolic Rate", val(scan.basal_metabolic_rate), "kcal"],
    ["Body Shape Index", val(scan.body_shape_index, 3), ""],
    ["Total Daily Energy", val(scan.total_daily_energy_expenditure), "kcal"],
  ];

  const hasIndices = indices.some(([, v]) => v !== "—");
  if (hasIndices) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...COLORS.foreground);
    y = checkPage(doc, y, 8);
    doc.text("Health Indices", 20, y);
    y += 5;
    for (const [label, value, unit] of indices) {
      if (value !== "—") y = drawVitalRow(doc, label, value, unit, y);
    }
    y += 3;
  }

  // Health Risks
  const risks: [string, string][] = [
    ["Cardiovascular Risk", riskLabel(scan.cv_disease_risk)],
    ["Coronary Heart Disease", riskLabel(scan.coronary_heart_disease_risk)],
    ["Stroke Risk", riskLabel(scan.stroke_risk)],
    ["Heart Failure Risk", riskLabel(scan.heart_failure_risk)],
    ["Diabetes Risk", riskLabel(scan.diabetes_risk)],
    ["Fatty Liver Disease", fattyLiverLabel(scan.fatty_liver_risk)],
    ["Cardiovascular Event", riskLabel(scan.hard_cv_event_risk)],
  ];

  const hasRisks = risks.some(([, v]) => v !== "—");
  if (hasRisks) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...COLORS.foreground);
    y = checkPage(doc, y, 8);
    doc.text("Health Risks", 20, y);
    y += 5;
    for (const [label, level] of risks) {
      if (level !== "—") y = drawRiskRow(doc, label, level, y);
    }
    y += 3;
  }

  return y;
}

export function generateSingleScanPdf(scan: VitalScanData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = addHeader(doc, "Face Scan Report", "Vital Scan", scan.created_at || scan.date || new Date().toISOString());
  y = addScanBlock(doc, scan, y, false);
  addFooter(doc);
  return doc;
}

export function generateCombinedScansPdf(scans: VitalScanData[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const sorted = [...scans].sort((a, b) => new Date(b.created_at || b.date || 0).getTime() - new Date(a.created_at || a.date || 0).getTime());

  let y = addHeader(doc, `Face Scan History (${sorted.length} scans)`, "Combined Report", new Date().toISOString());

  // Summary table — compact comparison across scans
  if (sorted.length > 1) {
    y = addSection(doc, "Quick Comparison", y);
    const cols = sorted.slice(0, 6); // max 6 scans in comparison
    const colW = Math.min(28, 150 / cols.length);
    const startX = 45;

    // Date headers
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.primary);
    cols.forEach((s, i) => {
      const d = new Date(s.created_at || s.date || "");
      const label = !isNaN(d.getTime()) ? d.toLocaleDateString("en-US", { month: "short", day: "numeric" }) : `Scan ${i + 1}`;
      doc.text(label, startX + i * colW, y, { align: "center" });
    });
    y += 5;

    const compareRows: [string, (s: VitalScanData) => string][] = [
      ["Heart Rate", s => val(s.heart_rate)],
      ["Blood Pressure", s => s.systolic_bp && s.diastolic_bp ? `${Math.round(s.systolic_bp)}/${Math.round(s.diastolic_bp)}` : "—"],
      ["Breathing Rate", s => val(s.breathing_rate)],
      ["Stress Index", s => val(s.stress_index)],
      ["HRV", s => val(s.hrv_sdnn)],
      ["BMI", s => val(s.bmi, 1)],
      ["Wellness Score", s => val(s.wellness_score)],
    ];

    for (const [label, getter] of compareRows) {
      y = checkPage(doc, y, 5);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...COLORS.muted);
      doc.text(label, 20, y);
      doc.setTextColor(...COLORS.foreground);
      doc.setFont("helvetica", "bold");
      cols.forEach((s, i) => {
        doc.text(getter(s), startX + i * colW, y, { align: "center" });
      });
      y += 4.5;
    }
    y += 6;
  }

  // Detailed per-scan data
  y = addSection(doc, "Detailed Scan Results", y);
  for (let i = 0; i < sorted.length; i++) {
    y = addScanBlock(doc, sorted[i], y, true);
    if (i < sorted.length - 1) {
      y += 4;
      y = checkPage(doc, y, 30);
    }
  }

  addFooter(doc);
  return doc;
}

export function downloadSingleScanPdf(scan: VitalScanData) {
  const doc = generateSingleScanPdf(scan);
  const d = new Date(scan.created_at || scan.date || "");
  const dateStr = !isNaN(d.getTime()) ? d.toISOString().slice(0, 10) : "scan";
  doc.save(`Cira_Vital_Scan_${dateStr}.pdf`);
}

export function downloadCombinedScansPdf(scans: VitalScanData[]) {
  const doc = generateCombinedScansPdf(scans);
  doc.save(`Cira_Combined_Scans_${scans.length}_${Date.now()}.pdf`);
}
