/**
 * Generate a branded Cira PDF from report data
 * Uses jsPDF for client-side PDF generation
 */
import jsPDF from "jspdf";

// Cira brand colors (HSL converted to RGB)
const COLORS = {
  primary: [196, 64, 157] as [number, number, number],       // hsl(319,65%,56%) → pink
  primaryLight: [251, 100, 182] as [number, number, number],  // lighter pink
  foreground: [30, 20, 46] as [number, number, number],      // dark purple-black
  muted: [130, 117, 107] as [number, number, number],        // muted text
  border: [220, 213, 206] as [number, number, number],       // light border
  background: [247, 244, 239] as [number, number, number],   // cream bg
  cardBg: [252, 250, 248] as [number, number, number],       // slightly off-white card
  white: [255, 255, 255] as [number, number, number],
  emerald: [16, 185, 129] as [number, number, number],
  emeraldLight: [209, 250, 229] as [number, number, number],
  amber: [217, 119, 6] as [number, number, number],
  amberLight: [254, 243, 199] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  redLight: [254, 226, 226] as [number, number, number],
  purple: [158, 29, 244] as [number, number, number],
  purpleLight: [243, 232, 255] as [number, number, number],
};

function drawLine(doc: jsPDF, y: number, x1 = 20, x2 = 190) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(x1, y, x2, y);
}

function checkPage(doc: jsPDF, y: number, needed = 20): number {
  if (y + needed > 275) {
    doc.addPage();
    return 20;
  }
  return y;
}

function addSection(doc: jsPDF, title: string, y: number): number {
  y = checkPage(doc, y, 15);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.primary);
  doc.text(title.toUpperCase(), 20, y);
  y += 2;
  drawLine(doc, y, 20, 190);
  y += 6;
  doc.setTextColor(...COLORS.foreground);
  return y;
}

function addParagraph(doc: jsPDF, text: string, y: number, indent = 20): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.foreground);
  const lines = doc.splitTextToSize(text || "—", 165);
  for (const line of lines) {
    y = checkPage(doc, y);
    doc.text(line, indent, y);
    y += 4.5;
  }
  return y;
}

function addBullet(doc: jsPDF, text: string, y: number): number {
  y = checkPage(doc, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.foreground);
  doc.text("•", 24, y);
  const lines = doc.splitTextToSize(text, 155);
  for (const line of lines) {
    y = checkPage(doc, y);
    doc.text(line, 30, y);
    y += 4.5;
  }
  return y;
}

function addHeader(doc: jsPDF, title: string, type: string, date: string) {
  // Top bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, 210, 3, "F");

  // Logo text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.primary);
  doc.text("Cira", 20, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text("AI Health Nurse", 42, 18);

  // Format date nicely
  const formattedDate = (() => {
    try {
      const d = new Date(date);
      if (!isNaN(d.getTime())) return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
    } catch {}
    return date;
  })();

  // Report type badge + date on separate lines
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.primary);
  doc.text(type.toUpperCase(), 190, 10, { align: "right" });
  doc.setTextColor(...COLORS.muted);
  doc.text(formattedDate, 190, 15, { align: "right" });

  drawLine(doc, 24);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.foreground);
  const titleLines = doc.splitTextToSize(title, 170);
  let y = 32;
  for (const line of titleLines) {
    doc.text(line, 20, y);
    y += 6;
  }

  return y + 4;
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    // Bottom bar
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 294, 210, 3, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.muted);
    doc.text("Generated by Cira AI Health Nurse  •  For informational purposes only  •  Not a medical diagnosis", 105, 290, { align: "center" });
    doc.text(`Page ${i} of ${pages}`, 190, 290, { align: "right" });
  }
}

export function generateQuickAssessmentPdf(report: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const data = report.data || {};
  const date = report.date || report.created_at || new Date().toLocaleDateString();

  let y = addHeader(doc, report.title || "Quick Assessment Report", "Quick Assessment", date);

  // Summary
  y = addSection(doc, "Summary", y);
  y = addParagraph(doc, data.summary || report.summary || "", y);
  y += 4;

  // Possible Conditions
  if (data.possible_conditions?.length) {
    y = addSection(doc, "Possible Conditions", y);
    for (const cond of data.possible_conditions) {
      y = checkPage(doc, y, 14);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(cond.name || "", 24, y);

      if (cond.likelihood) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.muted);
        doc.text(`(${cond.likelihood})`, 24 + doc.getTextWidth((cond.name || "") + "  "), y);
        doc.setTextColor(...COLORS.foreground);
      }
      y += 5;
      if (cond.explanation) {
        y = addParagraph(doc, cond.explanation, y, 28);
      }
      y += 2;
    }
    y += 2;
  }

  // Recommended Actions
  if (data.recommended_actions?.length) {
    y = addSection(doc, "Recommended Actions", y);
    for (const action of data.recommended_actions) {
      y = addBullet(doc, action, y);
    }
    y += 4;
  }

  // Follow-up
  if (data.follow_up) {
    y = addSection(doc, "Follow-Up", y);
    y = addParagraph(doc, data.follow_up, y);
  }

  // Confidence
  if (data.confidence_score != null) {
    y = checkPage(doc, y, 12);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Confidence Score: ${data.confidence_score}%`, 20, y);
  }

  addFooter(doc);
  return doc;
}

export function generateDetailedReportPdf(report: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const data = report.data || {};
  const date = report.date || report.created_at || new Date().toLocaleDateString();

  let y = addHeader(doc, report.title || "Detailed Assessment Report", "Detailed Assessment", date);

  // Patient Summary
  if (data.patient_summary) {
    y = addSection(doc, "Patient Summary", y);
    y = addParagraph(doc, data.patient_summary, y);
    y += 4;
  }

  // Chief Complaint
  if (data.chief_complaint) {
    y = addSection(doc, "Chief Complaint", y);
    y = addParagraph(doc, data.chief_complaint, y);
    y += 4;
  }

  // HPI
  if (data.history_of_present_illness) {
    y = addSection(doc, "History of Present Illness", y);
    y = addParagraph(doc, data.history_of_present_illness, y);
    y += 4;
  }

  // Review of Systems
  if (data.review_of_systems?.length) {
    y = addSection(doc, "Review of Systems", y);
    for (const ros of data.review_of_systems) {
      y = checkPage(doc, y, 10);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.text(ros.system || "", 24, y);
      y += 4.5;
      y = addParagraph(doc, ros.findings || "", y, 28);
      y += 2;
    }
    y += 2;
  }

  // Assessment
  if (data.assessment) {
    y = addSection(doc, "Assessment", y);
    if (data.assessment.primary_diagnosis) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Primary Diagnosis:", 24, y);
      doc.setFont("helvetica", "normal");
      doc.text(data.assessment.primary_diagnosis, 60, y);
      y += 5;
    }
    if (data.assessment.severity) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Severity:", 24, y);
      doc.setFont("helvetica", "normal");
      const sev = data.assessment.severity;
      const sevColor = sev === "severe" ? COLORS.red : sev === "moderate" ? COLORS.amber : COLORS.emerald;
      doc.setTextColor(...sevColor);
      doc.text(sev.charAt(0).toUpperCase() + sev.slice(1), 45, y);
      doc.setTextColor(...COLORS.foreground);
      y += 5;
    }
    if (data.assessment.differential_diagnoses?.length) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Differential Diagnoses:", 24, y);
      y += 5;
      for (const dd of data.assessment.differential_diagnoses) {
        y = addBullet(doc, `${dd.name}${dd.likelihood ? ` — ${dd.likelihood}` : ""}`, y);
      }
    }
    y += 4;
  }

  // Plan
  if (data.plan) {
    y = addSection(doc, "Treatment Plan", y);

    if (data.plan.immediate_actions?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Immediate Actions", 24, y);
      y += 5;
      for (const a of data.plan.immediate_actions) y = addBullet(doc, a, y);
      y += 3;
    }
    if (data.plan.medications_suggested?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Medications Suggested", 24, y);
      y += 5;
      for (const m of data.plan.medications_suggested) y = addBullet(doc, m, y);
      y += 3;
    }
    if (data.plan.lifestyle_recommendations?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Lifestyle Recommendations", 24, y);
      y += 5;
      for (const l of data.plan.lifestyle_recommendations) y = addBullet(doc, l, y);
      y += 3;
    }
    if (data.plan.follow_up) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Follow-Up", 24, y);
      y += 5;
      y = addParagraph(doc, data.plan.follow_up, y, 28);
    }
    y += 4;
  }

  // Red Flags
  if (data.red_flags?.length) {
    y = addSection(doc, "⚠ Red Flags", y);
    for (const flag of data.red_flags) {
      y = checkPage(doc, y);
      doc.setTextColor(...COLORS.red);
      y = addBullet(doc, flag, y);
      doc.setTextColor(...COLORS.foreground);
    }
    y += 4;
  }

  // Confidence
  if (data.confidence_score != null) {
    y = checkPage(doc, y, 12);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Confidence Score: ${data.confidence_score}%`, 20, y);
  }

  addFooter(doc);
  return doc;
}

export function downloadReportPdf(report: any) {
  const isDetailed = (report.type || "").toLowerCase().includes("detailed");
  const doc = isDetailed
    ? generateDetailedReportPdf(report)
    : generateQuickAssessmentPdf(report);

  const filename = `Cira_${(report.type || "Report").replace(/\s+/g, "_")}_${report.id || Date.now()}.pdf`;
  doc.save(filename);
}

// ─── Vitals Scan PDF ────────────────────────────────────────────

interface VitalScanData {
  id?: string;
  created_at?: string;
  date?: string;
  heart_rate?: number;
  systolic_bp?: number;
  diastolic_bp?: number;
  hrv_sdnn?: number;
  breathing_rate?: number;
  stress_index?: number;
  cardiac_workload?: number;
  parasympathetic_activity?: number;
  bmi?: number;
  vascular_age?: number;
  wellness_score?: number;
  waist_to_height_ratio?: number;
  body_fat_percentage?: number;
  basal_metabolic_rate?: number;
  body_shape_index?: number;
  total_daily_energy_expenditure?: number;
  cv_disease_risk?: number;
  coronary_heart_disease_risk?: number;
  stroke_risk?: number;
  heart_failure_risk?: number;
  diabetes_risk?: number;
  fatty_liver_risk?: number;
  hard_cv_event_risk?: number;
  [key: string]: any;
}

function formatScanDate(d?: string): string {
  if (!d) return "N/A";
  try {
    const date = new Date(d);
    if (!isNaN(date.getTime())) return date.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
  } catch {}
  return d;
}

function formatShortDate(d?: string): string {
  if (!d) return "N/A";
  try {
    const date = new Date(d);
    if (!isNaN(date.getTime())) return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
  } catch {}
  return d;
}

function val(v: number | null | undefined, decimals = 0): string {
  if (v == null) return "—";
  return decimals > 0 ? Number(v).toFixed(decimals) : String(Math.round(v));
}

function riskLabel(v: number | null | undefined): string {
  if (v == null) return "—";
  if (v < 10) return "Low";
  if (v < 25) return "Moderate";
  return "High";
}

function fattyLiverLabel(v: number | null | undefined): string {
  if (v == null) return "—";
  if (v === 0) return "Low";
  if (v === 1) return "Moderate";
  if (v === 2) return "High";
  return riskLabel(v);
}

function riskBadgeColors(level: string): { text: [number, number, number]; bg: [number, number, number] } {
  if (level === "Low") return { text: COLORS.emerald, bg: COLORS.emeraldLight };
  if (level === "Moderate") return { text: COLORS.amber, bg: COLORS.amberLight };
  if (level === "High") return { text: COLORS.red, bg: COLORS.redLight };
  return { text: COLORS.muted, bg: COLORS.cardBg };
}

// ─── Drawing helpers for professional cards ─────────────────────

function drawRoundedRect(doc: jsPDF, x: number, y: number, w: number, h: number, r: number, fillColor: [number, number, number], borderColor?: [number, number, number]) {
  doc.setFillColor(...fillColor);
  if (borderColor) {
    doc.setDrawColor(...borderColor);
    doc.setLineWidth(0.3);
  }
  doc.roundedRect(x, y, w, h, r, r, borderColor ? "FD" : "F");
}

function drawCiraLogo(doc: jsPDF, x: number, y: number, size: number) {
  const cx = x + size / 2;
  const cy = y + size / 2;
  const r = size / 2;
  
  // Pink circle background
  doc.setFillColor(...COLORS.primary);
  doc.circle(cx, cy, r, "F");
  
  // White "C" letter in center
  doc.setFont("helvetica", "bold");
  doc.setFontSize(size * 0.65);
  doc.setTextColor(255, 255, 255);
  doc.text("C", cx, cy + size * 0.12, { align: "center" });
}

function drawScanHeader(doc: jsPDF, title: string, subtitle: string, date: string): number {
  // Top gradient bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, 210, 4, "F");
  doc.setFillColor(...COLORS.primaryLight);
  doc.rect(140, 0, 70, 4, "F");

  // Logo circle + brand
  drawCiraLogo(doc, 18, 10, 10);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.foreground);
  doc.text("Cira", 32, 17);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.primary);
  doc.text("AI Health Nurse", 47, 17);

  // Right side: report type badge
  const badgeW = 40;
  drawRoundedRect(doc, 190 - badgeW, 8, badgeW, 7, 2, COLORS.purpleLight);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.purple);
  doc.text(subtitle.toUpperCase(), 190 - badgeW / 2, 13, { align: "center" });

  // Date below badge
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.muted);
  doc.text(formatShortDate(date), 190 - badgeW / 2, 19, { align: "center" });

  // Separator
  drawLine(doc, 24, 18, 192);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.foreground);
  const titleLines = doc.splitTextToSize(title, 170);
  let y = 32;
  for (const line of titleLines) {
    doc.text(line, 20, y);
    y += 6;
  }

  return y + 2;
}

function drawScanFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    
    // Disclaimer box
    const disclaimerY = 276;
    drawRoundedRect(doc, 15, disclaimerY, 180, 12, 2, COLORS.cardBg, COLORS.border);
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(...COLORS.primary);
    doc.text("MEDICAL DISCLAIMER", 20, disclaimerY + 4);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(5.5);
    doc.setTextColor(...COLORS.muted);
    doc.text("Cira is an AI health nurse, not a licensed medical professional. This report is for informational purposes only.", 20, disclaimerY + 7.5);
    doc.text("Always discuss these findings with your doctor. Trained on peer-reviewed medical data worldwide.", 20, disclaimerY + 10.5);

    // Bottom bar
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 294, 210, 3, "F");
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(...COLORS.muted);
    doc.text("Generated by Cira  •  askainurse.com", 105, 292, { align: "center" });
    doc.text(`Page ${i} of ${pages}`, 192, 292, { align: "right" });
  }
}

function drawSectionIcon(doc: jsPDF, type: string, x: number, y: number) {
  // Draw a small colored circle with a shape inside instead of emoji
  const colors: Record<string, [number, number, number]> = {
    vital: COLORS.primary,
    index: COLORS.emerald,
    risk: COLORS.amber,
    compare: COLORS.purple,
    detail: COLORS.primary,
  };
  const color = colors[type] || COLORS.primary;
  doc.setFillColor(...color);
  doc.circle(x + 3, y - 1, 3, "F");
  // White dot/letter inside
  doc.setFont("helvetica", "bold");
  doc.setFontSize(4.5);
  doc.setTextColor(255, 255, 255);
  const letters: Record<string, string> = { vital: "V", index: "I", risk: "R", compare: "C", detail: "D" };
  doc.text(letters[type] || "+", x + 3, y + 0.2, { align: "center" });
}

function drawSectionTitle(doc: jsPDF, title: string, y: number, iconType?: string): number {
  y = checkPage(doc, y, 14);
  
  const hasIcon = !!iconType;
  if (hasIcon) {
    drawSectionIcon(doc, iconType!, 20, y);
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(...COLORS.primary);
  doc.text(title, hasIcon ? 29 : 20, y);
  y += 2;
  
  // Thin accent line
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(hasIcon ? 29 : 20, y, 80, y);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.line(80, y, 192, y);
  
  return y + 5;
}

function drawVitalCard(doc: jsPDF, label: string, value: string, unit: string, x: number, y: number, w: number, h: number): void {
  drawRoundedRect(doc, x, y, w, h, 2.5, COLORS.cardBg, COLORS.border);
  
  // Label — truncate to fit card
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...COLORS.muted);
  const truncLabel = doc.splitTextToSize(label, w - 8)[0] || label;
  doc.text(truncLabel, x + 3.5, y + 5);
  
  // Value
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.foreground);
  const truncVal = doc.splitTextToSize(value, w - 8)[0] || value;
  doc.text(truncVal, x + 3.5, y + 12);
  
  // Unit
  if (unit && value !== "—") {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(...COLORS.muted);
    const valW = doc.getTextWidth(truncVal);
    if (valW + 10 < w - 4) {
      doc.text(unit, x + 3.5 + valW + 1.5, y + 12);
    }
  }
}

function drawRiskBadge(doc: jsPDF, label: string, level: string, x: number, y: number, w: number, h: number): void {
  drawRoundedRect(doc, x, y, w, h, 2.5, COLORS.cardBg, COLORS.border);
  
  // Label
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...COLORS.muted);
  const truncRiskLabel = doc.splitTextToSize(label, w - 8)[0] || label;
  doc.text(truncRiskLabel, x + 3.5, y + 5);
  
  // Risk badge pill
  const { text, bg } = riskBadgeColors(level);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  const badgeW = Math.max(doc.getTextWidth(level) + 5, 14);
  drawRoundedRect(doc, x + 3.5, y + 7.5, badgeW, 5, 1.5, bg);
  doc.setTextColor(...text);
  doc.text(level, x + 3.5 + badgeW / 2, y + 11, { align: "center" });
}

function addScanBlockPro(doc: jsPDF, scan: VitalScanData, y: number, showDate = true): number {
  if (showDate) {
    y = checkPage(doc, y, 12);
    // Date banner
    drawRoundedRect(doc, 20, y - 3, 172, 8, 2, COLORS.purpleLight);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.purple);
    doc.text(formatScanDate(scan.created_at || scan.date), 26, y + 2);
    y += 10;
  }

  // Vital Signs cards
  const vitals = ([
    ["Blood Pressure", scan.systolic_bp && scan.diastolic_bp ? `${Math.round(scan.systolic_bp)}/${Math.round(scan.diastolic_bp)}` : "—", "mmHg"],
    ["Heart Rate", val(scan.heart_rate), "bpm"],
    ["HRV (SDNN)", val(scan.hrv_sdnn), "ms"],
    ["Breathing Rate", val(scan.breathing_rate), "/min"],
    ["Stress Index", val(scan.stress_index), "/100"],
    ["Cardiac Workload", val(scan.cardiac_workload), ""],
    ["Parasympathetic", val(scan.parasympathetic_activity), ""],
  ] as [string, string, string][]).filter(([, v]) => v !== "—");

  if (vitals.length > 0) {
    y = drawSectionTitle(doc, "Vital Signs", y, "vital");
    const cardW = 40;
    const cardH = 16;
    const gap = 3;
    const cols = 4;
    for (let i = 0; i < vitals.length; i++) {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const cx = 20 + col * (cardW + gap);
      const cy = y + row * (cardH + gap);
      if (i === 0 || col === 0) {
        const neededY = cy + cardH;
        if (neededY > 270) {
          doc.addPage();
          y = 20;
        }
      }
      drawVitalCard(doc, vitals[i][0], vitals[i][1], vitals[i][2], cx, y + row * (cardH + gap), cardW, cardH);
    }
    y += Math.ceil(vitals.length / cols) * (cardH + gap) + 4;
  }

  // Health Indices cards
  const indices = ([
    ["BMI", val(scan.bmi, 1), "kg/m²"],
    ["Vascular Age", val(scan.vascular_age), "yrs"],
    ["Wellness Score", val(scan.wellness_score), "/100"],
    ["Waist:Height", val(scan.waist_to_height_ratio, 2), ""],
    ["Body Fat", val(scan.body_fat_percentage, 1), "%"],
    ["BMR", val(scan.basal_metabolic_rate), "kcal"],
    ["Body Shape", val(scan.body_shape_index, 3), ""],
    ["Daily Energy", val(scan.total_daily_energy_expenditure), "kcal"],
  ] as [string, string, string][]).filter(([, v]) => v !== "—");

  if (indices.length > 0) {
    y = drawSectionTitle(doc, "Health Indices", y, "index");
    const cardW = 40;
    const cardH = 16;
    const gap = 3;
    const cols = 4;
    for (let i = 0; i < indices.length; i++) {
      const col = i % cols;
      const row = Math.floor(i / cols);
      if (col === 0 && y + row * (cardH + gap) + cardH > 270) {
        doc.addPage();
        y = 20;
      }
      drawVitalCard(doc, indices[i][0], indices[i][1], indices[i][2], 20 + col * (cardW + gap), y + row * (cardH + gap), cardW, cardH);
    }
    y += Math.ceil(indices.length / cols) * (cardH + gap) + 4;
  }

  // Health Risks badges
  const risks = ([
    ["Cardiovascular", riskLabel(scan.cv_disease_risk)],
    ["Coronary Heart", riskLabel(scan.coronary_heart_disease_risk)],
    ["Stroke", riskLabel(scan.stroke_risk)],
    ["Heart Failure", riskLabel(scan.heart_failure_risk)],
    ["Diabetes", riskLabel(scan.diabetes_risk)],
    ["Fatty Liver", fattyLiverLabel(scan.fatty_liver_risk)],
    ["CV Event", riskLabel(scan.hard_cv_event_risk)],
  ] as [string, string][]).filter(([, v]) => v !== "—");

  if (risks.length > 0) {
    y = drawSectionTitle(doc, "Health Risks", y, "risk");
    const cardW = 40;
    const cardH = 16;
    const gap = 3;
    const cols = 4;
    for (let i = 0; i < risks.length; i++) {
      const col = i % cols;
      const row = Math.floor(i / cols);
      if (col === 0 && y + row * (cardH + gap) + cardH > 270) {
        doc.addPage();
        y = 20;
      }
      drawRiskBadge(doc, risks[i][0], risks[i][1], 20 + col * (cardW + gap), y + row * (cardH + gap), cardW, cardH);
    }
    y += Math.ceil(risks.length / cols) * (cardH + gap) + 4;
  }

  return y;
}

export function generateSingleScanPdf(scan: VitalScanData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = drawScanHeader(doc, "Face Scan Report", "Vital Scan", scan.created_at || scan.date || new Date().toISOString());
  y = addScanBlockPro(doc, scan, y, false);
  drawScanFooter(doc);
  return doc;
}

export function generateCombinedScansPdf(scans: VitalScanData[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const sorted = [...scans].sort((a, b) => new Date(b.created_at || b.date || 0).getTime() - new Date(a.created_at || a.date || 0).getTime());

  let y = drawScanHeader(doc, `Face Scan History`, "Combined Report", new Date().toISOString());

  // Patient summary line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(`${sorted.length} scans included  •  Most recent first`, 20, y);
  y += 8;

  // Quick Comparison Table (if multiple scans)
  if (sorted.length > 1) {
    y = drawSectionTitle(doc, "Scan Comparison", y, "compare");
    
    const cols = sorted.slice(0, 6);
    const labelW = 38;
    const colW = Math.min(25, (172 - labelW) / cols.length);
    const startX = 20 + labelW;
    const tableX = 20;
    const tableW = labelW + cols.length * colW;
    
    // Table header row
    drawRoundedRect(doc, tableX, y - 1, tableW, 7, 1.5, COLORS.purpleLight);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(...COLORS.purple);
    doc.text("Metric", tableX + 3, y + 3);
    cols.forEach((s, i) => {
      const d = new Date(s.created_at || s.date || "");
      const label = !isNaN(d.getTime()) ? d.toLocaleDateString("en-US", { month: "short", day: "numeric" }) : `#${i + 1}`;
      doc.text(label, startX + i * colW + colW / 2, y + 3, { align: "center" });
    });
    y += 9;

    const compareRows: [string, (s: VitalScanData) => string][] = [
      ["Heart Rate (bpm)", s => val(s.heart_rate)],
      ["Blood Pressure", s => s.systolic_bp && s.diastolic_bp ? `${Math.round(s.systolic_bp)}/${Math.round(s.diastolic_bp)}` : "—"],
      ["Breathing Rate", s => val(s.breathing_rate)],
      ["Stress Index", s => val(s.stress_index)],
      ["HRV (ms)", s => val(s.hrv_sdnn)],
      ["BMI", s => val(s.bmi, 1)],
      ["Wellness Score", s => val(s.wellness_score)],
      ["Vascular Age", s => val(s.vascular_age)],
    ];

    compareRows.forEach(([label, getter], rowIdx) => {
      y = checkPage(doc, y, 6);
      const isAlt = rowIdx % 2 === 0;
      if (isAlt) {
        doc.setFillColor(...COLORS.cardBg);
        doc.rect(tableX, y - 3, tableW, 5.5, "F");
      }
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.muted);
      doc.text(label, tableX + 3, y);
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(...COLORS.foreground);
      cols.forEach((s, i) => {
        doc.text(getter(s), startX + i * colW + colW / 2, y, { align: "center" });
      });
      y += 5.5;
    });
    y += 6;
  }

  // Detailed per-scan data
  y = drawSectionTitle(doc, "Individual Scan Details", y, "detail");
  for (let i = 0; i < sorted.length; i++) {
    y = addScanBlockPro(doc, sorted[i], y, true);
    if (i < sorted.length - 1) {
      y += 2;
      y = checkPage(doc, y, 40);
    }
  }

  drawScanFooter(doc);
  return doc;
}

export function downloadSingleScanPdf(scan: VitalScanData) {
  const doc = generateSingleScanPdf(scan);
  const d = new Date(scan.created_at || scan.date || "");
  const dateStr = !isNaN(d.getTime()) ? d.toISOString().slice(0, 10) : "scan";
  doc.save(`Cira_Vital_Scan_${dateStr}.pdf`);
}

export function downloadCombinedScansPdf(scans: VitalScanData[]) {
  const doc = generateCombinedScansPdf(scans);
  doc.save(`Cira_Combined_Scans_${scans.length}_${Date.now()}.pdf`);
}
