/**
 * Generate a branded Cira PDF from report data
 * Uses jsPDF for client-side PDF generation
 */
import jsPDF from "jspdf";

// Cira brand colors (HSL converted to RGB)
const COLORS = {
  primary: [196, 64, 157] as [number, number, number],       // hsl(319,65%,56%) → pink
  foreground: [30, 20, 46] as [number, number, number],      // dark purple-black
  muted: [130, 117, 107] as [number, number, number],        // muted text
  border: [220, 213, 206] as [number, number, number],       // light border
  background: [247, 244, 239] as [number, number, number],   // cream bg
  white: [255, 255, 255] as [number, number, number],
  emerald: [16, 185, 129] as [number, number, number],
  amber: [217, 119, 6] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
};

function drawLine(doc: jsPDF, y: number, x1 = 20, x2 = 190) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(x1, y, x2, y);
}

function checkPage(doc: jsPDF, y: number, needed = 20): number {
  if (y + needed > 275) {
    doc.addPage();
    return 20;
  }
  return y;
}

function addSection(doc: jsPDF, title: string, y: number): number {
  y = checkPage(doc, y, 15);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.primary);
  doc.text(title.toUpperCase(), 20, y);
  y += 2;
  drawLine(doc, y, 20, 190);
  y += 6;
  doc.setTextColor(...COLORS.foreground);
  return y;
}

function addParagraph(doc: jsPDF, text: string, y: number, indent = 20): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.foreground);
  const lines = doc.splitTextToSize(text || "—", 165);
  for (const line of lines) {
    y = checkPage(doc, y);
    doc.text(line, indent, y);
    y += 4.5;
  }
  return y;
}

function addBullet(doc: jsPDF, text: string, y: number): number {
  y = checkPage(doc, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...COLORS.foreground);
  doc.text("•", 24, y);
  const lines = doc.splitTextToSize(text, 155);
  for (const line of lines) {
    y = checkPage(doc, y);
    doc.text(line, 30, y);
    y += 4.5;
  }
  return y;
}

function addHeader(doc: jsPDF, title: string, type: string, date: string) {
  // Top bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, 210, 3, "F");

  // Logo text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.primary);
  doc.text("Cira", 20, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text("AI Health Nurse", 42, 18);

  // Report type badge
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.primary);
  doc.text(type.toUpperCase(), 170, 12, { align: "right" });

  // Date
  doc.setTextColor(...COLORS.muted);
  doc.text(date, 190, 12, { align: "right" });

  drawLine(doc, 24);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.foreground);
  const titleLines = doc.splitTextToSize(title, 170);
  let y = 32;
  for (const line of titleLines) {
    doc.text(line, 20, y);
    y += 6;
  }

  return y + 4;
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    // Bottom bar
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 294, 210, 3, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.muted);
    doc.text("Generated by Cira AI Health Nurse  •  For informational purposes only  •  Not a medical diagnosis", 105, 290, { align: "center" });
    doc.text(`Page ${i} of ${pages}`, 190, 290, { align: "right" });
  }
}

export function generateQuickAssessmentPdf(report: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const data = report.data || {};
  const date = report.date || report.created_at || new Date().toLocaleDateString();

  let y = addHeader(doc, report.title || "Quick Assessment Report", "Quick Assessment", date);

  // Summary
  y = addSection(doc, "Summary", y);
  y = addParagraph(doc, data.summary || report.summary || "", y);
  y += 4;

  // Possible Conditions
  if (data.possible_conditions?.length) {
    y = addSection(doc, "Possible Conditions", y);
    for (const cond of data.possible_conditions) {
      y = checkPage(doc, y, 14);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(cond.name || "", 24, y);

      if (cond.likelihood) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.muted);
        doc.text(`(${cond.likelihood})`, 24 + doc.getTextWidth((cond.name || "") + "  "), y);
        doc.setTextColor(...COLORS.foreground);
      }
      y += 5;
      if (cond.explanation) {
        y = addParagraph(doc, cond.explanation, y, 28);
      }
      y += 2;
    }
    y += 2;
  }

  // Recommended Actions
  if (data.recommended_actions?.length) {
    y = addSection(doc, "Recommended Actions", y);
    for (const action of data.recommended_actions) {
      y = addBullet(doc, action, y);
    }
    y += 4;
  }

  // Follow-up
  if (data.follow_up) {
    y = addSection(doc, "Follow-Up", y);
    y = addParagraph(doc, data.follow_up, y);
  }

  // Confidence
  if (data.confidence_score != null) {
    y = checkPage(doc, y, 12);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Confidence Score: ${data.confidence_score}%`, 20, y);
  }

  addFooter(doc);
  return doc;
}

export function generateDetailedReportPdf(report: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const data = report.data || {};
  const date = report.date || report.created_at || new Date().toLocaleDateString();

  let y = addHeader(doc, report.title || "Detailed Assessment Report", "Detailed Assessment", date);

  // Patient Summary
  if (data.patient_summary) {
    y = addSection(doc, "Patient Summary", y);
    y = addParagraph(doc, data.patient_summary, y);
    y += 4;
  }

  // Chief Complaint
  if (data.chief_complaint) {
    y = addSection(doc, "Chief Complaint", y);
    y = addParagraph(doc, data.chief_complaint, y);
    y += 4;
  }

  // HPI
  if (data.history_of_present_illness) {
    y = addSection(doc, "History of Present Illness", y);
    y = addParagraph(doc, data.history_of_present_illness, y);
    y += 4;
  }

  // Review of Systems
  if (data.review_of_systems?.length) {
    y = addSection(doc, "Review of Systems", y);
    for (const ros of data.review_of_systems) {
      y = checkPage(doc, y, 10);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.text(ros.system || "", 24, y);
      y += 4.5;
      y = addParagraph(doc, ros.findings || "", y, 28);
      y += 2;
    }
    y += 2;
  }

  // Assessment
  if (data.assessment) {
    y = addSection(doc, "Assessment", y);
    if (data.assessment.primary_diagnosis) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Primary Diagnosis:", 24, y);
      doc.setFont("helvetica", "normal");
      doc.text(data.assessment.primary_diagnosis, 60, y);
      y += 5;
    }
    if (data.assessment.severity) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Severity:", 24, y);
      doc.setFont("helvetica", "normal");
      const sev = data.assessment.severity;
      const sevColor = sev === "severe" ? COLORS.red : sev === "moderate" ? COLORS.amber : COLORS.emerald;
      doc.setTextColor(...sevColor);
      doc.text(sev.charAt(0).toUpperCase() + sev.slice(1), 45, y);
      doc.setTextColor(...COLORS.foreground);
      y += 5;
    }
    if (data.assessment.differential_diagnoses?.length) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Differential Diagnoses:", 24, y);
      y += 5;
      for (const dd of data.assessment.differential_diagnoses) {
        y = addBullet(doc, `${dd.name}${dd.likelihood ? ` — ${dd.likelihood}` : ""}`, y);
      }
    }
    y += 4;
  }

  // Plan
  if (data.plan) {
    y = addSection(doc, "Treatment Plan", y);

    if (data.plan.immediate_actions?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Immediate Actions", 24, y);
      y += 5;
      for (const a of data.plan.immediate_actions) y = addBullet(doc, a, y);
      y += 3;
    }
    if (data.plan.medications_suggested?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Medications Suggested", 24, y);
      y += 5;
      for (const m of data.plan.medications_suggested) y = addBullet(doc, m, y);
      y += 3;
    }
    if (data.plan.lifestyle_recommendations?.length) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Lifestyle Recommendations", 24, y);
      y += 5;
      for (const l of data.plan.lifestyle_recommendations) y = addBullet(doc, l, y);
      y += 3;
    }
    if (data.plan.follow_up) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      y = checkPage(doc, y);
      doc.text("Follow-Up", 24, y);
      y += 5;
      y = addParagraph(doc, data.plan.follow_up, y, 28);
    }
    y += 4;
  }

  // Red Flags
  if (data.red_flags?.length) {
    y = addSection(doc, "⚠ Red Flags", y);
    for (const flag of data.red_flags) {
      y = checkPage(doc, y);
      doc.setTextColor(...COLORS.red);
      y = addBullet(doc, flag, y);
      doc.setTextColor(...COLORS.foreground);
    }
    y += 4;
  }

  // Confidence
  if (data.confidence_score != null) {
    y = checkPage(doc, y, 12);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Confidence Score: ${data.confidence_score}%`, 20, y);
  }

  addFooter(doc);
  return doc;
}

export function downloadReportPdf(report: any) {
  const isDetailed = (report.type || "").toLowerCase().includes("detailed");
  const doc = isDetailed
    ? generateDetailedReportPdf(report)
    : generateQuickAssessmentPdf(report);

  const filename = `Cira_${(report.type || "Report").replace(/\s+/g, "_")}_${report.id || Date.now()}.pdf`;
  doc.save(filename);
}
