import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Home, LogOut, ScanFace, Sparkles, FileText, Download, Eye, Calendar, Search, UserRound } from "lucide-react";
import ciraLogo from "@/assets/cira-logo.svg";
import ProfilePopover from "@/components/ProfilePopover";
import AiSparkleIcon from "@/components/AiSparkleIcon";
import MobileBottomNav from "@/components/MobileBottomNav";

const navItems = [
  { icon: Home, label: "Home", id: "home" },
  { icon: Sparkles, label: "Ask Cira", id: "chat" },
  { icon: ScanFace, label: "Scan", id: "scan" },
  { icon: FileText, label: "Reports", id: "reports" },
  { icon: UserRound, label: "Doctor", id: "doctor" },
];

const mockReports = [
  {
    id: "RPT-001",
    title: "Detailed Health Assessment Report",
    date: "Mar 29, 2026",
    size: "2.4 MB",
    status: "Ready",
    summary: "Comprehensive health evaluation based on 28 questions and vital scan data. Covers cardiovascular, metabolic, and mental health indicators.",
  },
  {
    id: "RPT-002",
    title: "Detailed Assessment — Chronic Fatigue",
    date: "Mar 15, 2026",
    size: "3.1 MB",
    status: "Ready",
    summary: "In-depth analysis of chronic fatigue symptoms with lifestyle, sleep, and stress correlation report.",
  },
  {
    id: "RPT-003",
    title: "Detailed Assessment — Annual Review",
    date: "Feb 28, 2026",
    size: "4.1 MB",
    status: "Ready",
    summary: "Annual comprehensive health review with year-over-year trend analysis and personalized recommendations.",
  },
  {
    id: "RPT-004",
    title: "Detailed Assessment — Digestive Health",
    date: "Jan 20, 2026",
    size: "2.8 MB",
    status: "Ready",
    summary: "Thorough digestive health evaluation covering diet, symptoms, and gut health indicators.",
  },
];


const Reports = () => {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState("");
  const [previewId, setPreviewId] = useState<string | null>(null);

  const filteredReports = mockReports.filter((r) =>
    r.title.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleDownload = (report: typeof mockReports[0]) => {
    // Mock download - in production this would fetch the actual PDF
    const blob = new Blob([`Mock PDF content for: ${report.title}\n\nGenerated by Cira Health AI\nDate: ${report.date}\n\n${report.summary}`], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.id}_${report.title.replace(/\s+/g, "_")}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex bg-background" style={{ height: '100dvh' }}>
      {/* Sidebar — hidden on mobile */}
      <div className="hidden md:flex w-[72px] border-r border-border bg-card flex-col items-center py-4 shrink-0">
        <div className="mb-4">
          <img src={ciraLogo} alt="Cira" width={28} height={28} />
        </div>
        <div className="w-10 h-[1px] bg-border mb-3" />
        <div className="flex-1 flex flex-col items-center gap-1">
          {navItems.map((item) => {
            const Icon = item.icon;
            return (
              <button
                key={item.id}
                onClick={() => {
                  if (item.id === "home") navigate("/dashboard");
                  if (item.id === "chat") navigate("/chat");
                  if (item.id === "scan") navigate("/vitals-scan");
                   if (item.id === "reports") navigate("/reports");
                   if (item.id === "doctor") navigate("/doctor");
                }}
                className={`w-14 py-2 rounded-xl flex flex-col items-center gap-0.5 transition-all ${
                  item.id === "reports"
                    ? "bg-primary/10 text-primary"
                    : "text-muted-foreground hover:bg-accent hover:text-foreground"
                }`}
              >
                {item.id === "chat" ? (
                  <AiSparkleIcon size={18} />
                ) : (
                  <Icon size={18} strokeWidth={item.id === "reports" ? 2 : 1.5} />
                )}
                <span className="text-[9px] font-body font-medium leading-none">{item.label}</span>
              </button>
            );
          })}
        </div>
        <div className="mt-auto flex flex-col items-center gap-2">
          <button
            onClick={() => navigate("/")}
            className="w-14 py-2 rounded-xl flex flex-col items-center gap-0.5 text-muted-foreground hover:bg-accent hover:text-foreground transition-all"
          >
            <LogOut size={18} strokeWidth={1.5} />
            <span className="text-[9px] font-body font-medium leading-none">Logout</span>
          </button>
          <ProfilePopover>
            <div className="w-9 h-9 rounded-full bg-gradient-to-br from-primary to-primary/60 flex items-center justify-center text-primary-foreground text-xs font-medium font-body cursor-pointer ring-2 ring-primary/20">
              AX
            </div>
          </ProfilePopover>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-y-auto relative">
        <div className="fixed inset-0 pointer-events-none md:left-[72px]">
          <div className="absolute inset-0 bg-gradient-to-br from-blue-100/50 via-pink-50/30 to-orange-50/40" />
          <div className="absolute top-0 left-0 w-[50%] h-[50%] bg-gradient-to-br from-blue-200/40 to-purple-100/20 rounded-full blur-[120px]" />
          <div className="absolute bottom-0 right-0 w-[50%] h-[50%] bg-gradient-to-tl from-orange-200/40 via-pink-100/30 to-rose-100/20 rounded-full blur-[120px]" />
        </div>

        <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-8 pb-24 md:pb-8">
          {/* Header */}
          <div className="flex items-start justify-between mb-8">
            <div>
              <h1 className="text-2xl font-semibold text-foreground mb-1" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>
                Reports
              </h1>
              <p className="text-sm text-muted-foreground font-body">View, download, and manage your health reports</p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground font-body">{filteredReports.length} reports</span>
            </div>
          </div>

          {/* Search Bar */}
          <div className="mb-6">
            <div className="relative">
              <Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search reports..."
                className="w-full h-10 rounded-xl border border-border/60 bg-card/80 backdrop-blur-sm pl-10 pr-4 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary/50 transition-all"
                style={{ fontFamily: "'Inter', system-ui, sans-serif" }}
              />
            </div>
          </div>

          {/* Reports List */}
          <div className="space-y-3">
            {filteredReports.map((report) => (
              <div
                key={report.id}
                className="bg-card/80 backdrop-blur-sm border border-border/50 rounded-2xl p-5 hover:shadow-md hover:border-border transition-all group"
              >
                <div className="flex items-start gap-4">
                  {/* Icon */}
                  <div className="w-12 h-12 rounded-xl bg-purple-50 flex items-center justify-center text-lg shrink-0">
                    📋
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-3 mb-1">
                      <h3 className="text-sm font-semibold text-foreground truncate" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>
                        {report.title}
                      </h3>
                      <span className="shrink-0 text-[10px] font-medium px-2.5 py-0.5 rounded-full text-purple-600 bg-purple-50">
                        Detailed Assessment
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground mb-3 line-clamp-2">{report.summary}</p>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4 text-[11px] text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Calendar size={12} />
                          {report.date}
                        </span>
                        <span>{report.size}</span>
                        <span className="text-emerald-600 font-medium">{report.status}</span>
                      </div>
                      <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button
                          onClick={() => setPreviewId(previewId === report.id ? null : report.id)}
                          className="h-8 px-3 rounded-lg border border-border/60 text-xs font-medium text-foreground hover:bg-accent transition-all flex items-center gap-1.5"
                        >
                          <Eye size={13} />
                          Preview
                        </button>
                        <button
                          onClick={() => handleDownload(report)}
                          className="h-8 px-3 rounded-lg bg-gradient-to-r from-primary to-primary/80 text-primary-foreground text-xs font-medium shadow-sm hover:shadow-md transition-all flex items-center gap-1.5"
                        >
                          <Download size={13} />
                          Download
                        </button>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Preview Panel */}
                {previewId === report.id && (
                  <div className="mt-4 pt-4 border-t border-border/40">
                    <div className="bg-secondary/30 rounded-xl p-5">
                      <div className="flex items-center gap-2 mb-3">
                        <FileText size={14} className="text-muted-foreground" />
                        <p className="text-xs font-semibold text-foreground" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>Report Preview</p>
                      </div>
                      <div className="space-y-2 text-xs text-muted-foreground leading-relaxed">
                        <p><span className="font-medium text-foreground">Report ID:</span> {report.id}</p>
                        <p><span className="font-medium text-foreground">Type:</span> Detailed Assessment</p>
                        <p><span className="font-medium text-foreground">Generated:</span> {report.date}</p>
                        <p><span className="font-medium text-foreground">Summary:</span> {report.summary}</p>
                        <p className="pt-2 text-[10px] text-muted-foreground/60">
                          ⚕️ This report was generated by Cira AI Health Nurse. Always discuss findings with a licensed medical professional.
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {filteredReports.length === 0 && (
            <div className="text-center py-16">
              <FileText size={40} className="text-muted-foreground/30 mx-auto mb-4" />
              <p className="text-sm text-muted-foreground">No reports found</p>
              <p className="text-xs text-muted-foreground/60 mt-1">Try adjusting your search or filter</p>
            </div>
          )}
        </div>
      </div>
      <MobileBottomNav />
    </div>
  );
};

export default Reports;
