import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import ciraLogo from "@/assets/cira-logo.svg";
import LandingMenu from "@/components/LandingMenu";

const Terms = () => {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <nav className="flex items-center justify-between px-6 py-5 max-w-4xl mx-auto">
        <div className="flex items-center gap-1">
          <LandingMenu />
          <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back
          </button>
        </div>
        <div className="flex items-center gap-2">
          <img src={ciraLogo} alt="Cira" width={24} height={24} />
          <span className="font-heading text-base font-semibold text-foreground">Cira</span>
        </div>
      </nav>

      <article className="max-w-3xl mx-auto px-6 pb-24 font-body text-foreground">
        <h1 className="font-heading text-3xl md:text-4xl font-semibold mb-2">Terms of Service</h1>
        <p className="text-xs text-muted-foreground mb-8">Last updated: April 22, 2026</p>

        <div className="space-y-6 text-sm leading-relaxed text-foreground/90">
          <p>
            These Terms of Service ("Terms") govern your access to and use of Cira (the "Service").
            By creating an account or otherwise using the Service, you agree to these Terms.
          </p>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">1. Not medical advice</h2>
            <p>
              Cira is an <strong>AI-powered health information assistant in beta</strong>. It is not a
              doctor, nurse, or licensed medical provider. Information provided by Cira is for general
              educational purposes only and is <strong>not a substitute for professional medical advice,
              diagnosis, or treatment</strong>. Always seek the advice of a qualified clinician with any
              questions you may have regarding a medical condition.
            </p>
            <p>
              <strong>In an emergency, call your local emergency number immediately.</strong>
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">2. Eligibility</h2>
            <p>You must be at least 16 years old to use Cira. You agree to provide accurate information.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">3. Account & security</h2>
            <p>
              You are responsible for safeguarding your account credentials and for all activity under
              your account. Notify us immediately of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">4. Acceptable use</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Do not use Cira to make critical medical decisions without professional review.</li>
              <li>Do not submit data on behalf of another person without their consent.</li>
              <li>Do not attempt to reverse-engineer, scrape, or disrupt the Service.</li>
              <li>Do not use the Service to violate any applicable law or regulation.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">5. Subscriptions & credits</h2>
            <p>
              Free accounts include a limited daily message and scan allowance. Paid plans grant
              additional usage as described at checkout. Charges are non-refundable except where
              required by law.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">6. AI-generated content</h2>
            <p>
              Cira's responses, assessments, and reports are generated by large language models and
              biometric models. They may be inaccurate, incomplete, or outdated. You are solely
              responsible for how you act on AI-generated information.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">7. Intellectual property</h2>
            <p>
              The Service, including its design, content, and software, is owned by Cira and protected
              by intellectual-property laws. We grant you a limited, non-exclusive, non-transferable
              license to use the Service for personal, non-commercial purposes.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">8. Privacy</h2>
            <p>
              Your use of Cira is also governed by our{" "}
              <button onClick={() => navigate("/privacy")} className="underline">Privacy Policy</button>.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">9. Termination</h2>
            <p>
              We may suspend or terminate your access at any time for breach of these Terms or for any
              lawful reason. You may close your account at any time from the profile page.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">10. Disclaimers</h2>
            <p className="uppercase text-xs">
              The Service is provided "as is" and "as available" without warranties of any kind, express
              or implied, including merchantability, fitness for a particular purpose, and non-infringement.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">11. Limitation of liability</h2>
            <p className="uppercase text-xs">
              To the maximum extent permitted by law, Cira and its affiliates shall not be liable for
              any indirect, incidental, special, consequential, or punitive damages, or any loss of
              profits or data, arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">12. Changes</h2>
            <p>
              We may modify these Terms. Material changes will be notified in-app or by email. Continued
              use after changes means you accept the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">13. Governing law</h2>
            <p>
              These Terms are governed by the laws of the jurisdiction where Cira is operated, without
              regard to conflict-of-law principles.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold mb-2">14. Contact</h2>
            <p>
              Questions: <a className="underline" href="mailto:legal@askainurse.com">legal@askainurse.com</a>.
            </p>
          </section>
        </div>
      </article>
    </div>
  );
};

export default Terms;
